// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_etn4oIzGDYbI4d2u4sJ1XJxjgozDqk',
    appId: '1:754787359209:web:ac24240cb4763d8e401378',
    messagingSenderId: '754787359209',
    projectId: 'bytebazaar-8289b',
    authDomain: 'bytebazaar-8289b.firebaseapp.com',
    storageBucket: 'bytebazaar-8289b.firebasestorage.app',
    measurementId: 'G-9ZP9T5YQ7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmijakR7fRVXeU2IMDWBPv-oyYtUcd8ac',
    appId: '1:754787359209:android:01c897e054c888f1401378',
    messagingSenderId: '754787359209',
    projectId: 'bytebazaar-8289b',
    storageBucket: 'bytebazaar-8289b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoB9_huzUDgrNylLTM3czPrUhgd144U9M',
    appId: '1:754787359209:ios:f7b52700f1161dfc401378',
    messagingSenderId: '754787359209',
    projectId: 'bytebazaar-8289b',
    storageBucket: 'bytebazaar-8289b.firebasestorage.app',
    iosBundleId: 'com.example.bytebazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoB9_huzUDgrNylLTM3czPrUhgd144U9M',
    appId: '1:754787359209:ios:f7b52700f1161dfc401378',
    messagingSenderId: '754787359209',
    projectId: 'bytebazaar-8289b',
    storageBucket: 'bytebazaar-8289b.firebasestorage.app',
    iosBundleId: 'com.example.bytebazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_etn4oIzGDYbI4d2u4sJ1XJxjgozDqk',
    appId: '1:754787359209:web:05d6f27adfa77302401378',
    messagingSenderId: '754787359209',
    projectId: 'bytebazaar-8289b',
    authDomain: 'bytebazaar-8289b.firebaseapp.com',
    storageBucket: 'bytebazaar-8289b.firebasestorage.app',
    measurementId: 'G-3XSC5SF454',
  );
}
